parameters:
  - name: environment
    type: string
  - name: serviceConnection
    type: string
  - name: adoEnvironment
    type: string
  - name: dependsOn
    type: string

jobs:
  - deployment: Apply
    dependsOn: ${{ parameters.dependsOn }}
    environment: ${{ parameters.adoEnvironment }}
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self
            
            - download: current
              artifact: tfplan-${{ parameters.environment }}
              displayName: 'Download Plan Artifact'
              
            - task: TerraformInstaller@1
              displayName: 'Install Terraform'
              inputs:
                terraformVersion: 'latest'
                
            - task: AzureCLI@2
              displayName: 'Terraform Init and Apply'
              inputs:
                azureSubscription: ${{ parameters.serviceConnection }}
                scriptType: 'bash'
                scriptLocation: 'inlineScript'
                inlineScript: |
                  # Move the downloaded tfplan to the environment directory
                  cp $(Pipeline.Workspace)/tfplan-${{ parameters.environment }}/tfplan environments/${{ parameters.environment }}/tfplan
                  cd environments/${{ parameters.environment }}
                  
                  terraform init -backend-config="resource_group_name=$(backendRg)" -backend-config="storage_account_name=$(backendStorage)" -backend-config="container_name=$(backendContainer)" -backend-config="key=${{ parameters.environment }}.terraform.tfstate"
                  
                  # Secure apply using ONLY the previously generated plan
                  terraform apply -auto-approve tfplan
